# Site settings
title: "JWD70"
email: bindel@cornell.edu
description:
  Conference in Honor of James W. Demmel on his 70th Birthday
baseurl: "/dmml/"
url: "https://www.dbindel.net" # the base hostname & protocol for your site

encoding: utf-8
timezone: America/New_York

# Build settings
markdown: kramdown
